document_management/doc_management/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.user_login, name='login'),  # 设置登陆页面URL对应的视图函数
    path('login/', views.user_login, name='login'),
    path('home/', views.home, name='home'),    # 设置文档管理页面URL对应的视图函数
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),  # 使用Django自带的LogoutView
    path('upload/', views.upload_document, name='upload_document'),
    path('batch_upload/', views.batch_upload_document, name='batch_upload_document'),
    path('preview/<int:document_id>/', views.preview_document, name='preview_document'),
    path('delete/<int:document_id>/', views.delete_document, name='delete_document'),
    path('request_preview/<int:document_id>/', views.request_preview, name='request_preview'),
    path('edit_document/<int:document_id>/', views.edit_document, name='edit_document'),

    path('payment_terms/', views.payment_terms_list, name='payment_terms_list'),
    path('payment_terms/add/', views.add_payment_term, name='add_payment_term'),
    path('payment_terms/edit/<int:payment_term_id>/', views.edit_payment_term, name='edit_payment_term'),
    path('payment_terms/delete/<int:payment_term_id>/', views.delete_payment_term, name='delete_payment_term'),



    # 添加其他URL配置
]

document_management/document_management/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('doc_management.urls')),
    path('', include('user_management.urls')),
    path('', include('system_config.urls')),

]

document_management/system_config/urls.py
# system_config/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('user_info/', views.user_info, name='user_info'),
    path('change_password/', auth_views.PasswordChangeView.as_view(), name='change_password'),
    path('password_change_done/', views.password_change_done, name='password_change_done'),

]

document_management/doc_management/models.py
# doc_management/models.py


from django.conf import settings
from django.db import models


class Document(models.Model):
    CONTRACT_CATEGORY_CHOICES = (
        ('paper', '纸质文档'),
        ('electronic', '电子文档'),
    )

    document_type = models.CharField(max_length=100)
    document_name = models.CharField(max_length=100)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    uploader = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    document_file = models.FileField(upload_to='documents/')

    contract_signature_date = models.DateField(null=True, blank=True)
    contract_expiry_date = models.DateField(null=True, blank=True)
    contract_amount_with_tax = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    contract_amount_without_tax = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    payment_terms = models.ForeignKey('doc_management.PaymentTerm', on_delete=models.SET_NULL, null=True, blank=True)

    contract_category = models.CharField(max_length=20, choices=CONTRACT_CATEGORY_CHOICES, default='paper')

    def __str__(self):
        return self.document_name


class PreviewRequest(models.Model):
    requester = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    document = models.ForeignKey(Document, on_delete=models.CASCADE)
    is_approved = models.BooleanField(default=False)
    approved_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='approved_requests', null=True, blank=True, on_delete=models.SET_NULL)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Preview request by {self.requester} for {self.document}"


class PaymentTerm(models.Model):
    abbreviation = models.CharField(max_length=20)
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.abbreviation

document_management/doc_management/views.py
# views.py
import os
from django.http import HttpResponse
import tempfile
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from .models import Document, PreviewRequest
from django.shortcuts import render, redirect, get_object_or_404
from .models import PaymentTerm
import datetime
from docx2pdf import convert


def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('home')

        else:
            messages.error(request, '帐号或者密码错误')
    else:
        form = AuthenticationForm()

    return render(request, 'doc_management/login.html', {'form': form})


def home(request):
    documents = Document.objects.order_by('-uploaded_at')  # 以上传时间降序排序
    paginator = Paginator(documents, 17)
    page_number = request.GET.get('page')
    page_documents = paginator.get_page(page_number)

    for document in page_documents:
        if document.previewrequest_set.filter(requester=request.user, is_approved=True).exists():
            document.is_approved_for_preview = True
            document.is_waiting_approval = False
        elif document.previewrequest_set.filter(requester=request.user, is_approved=False).exists():
            document.is_approved_for_preview = False
            document.is_waiting_approval = True
        else:
            document.is_approved_for_preview = False
            document.is_waiting_approval = False

    return render(request, 'doc_management/home.html', {'page_documents': page_documents})


def upload_document(request):
    existing_payment_terms = PaymentTerm.objects.all()  # 获取所有现有的对应系统

    if request.method == 'POST':
        document = request.FILES.get('document')
        if document:
            document_name = document.name
            uploader = request.user

            if Document.objects.filter(document_name=document_name).exists():
                message = "已上传过相同名称的文件，请修改文件名称后重新上传。"
                return redirect('home')

            # 获取用户输入的新字段值
            contract_category = request.POST.get('contract_category')
            contract_signature_date = request.POST.get('contract_signature_date')
            contract_expiry_date = request.POST.get('contract_expiry_date')
            contract_amount_with_tax = request.POST.get('contract_amount_with_tax')
            contract_amount_without_tax = request.POST.get('contract_amount_without_tax')
            payment_terms_id = request.POST.get('payment_terms')  # 获取用户选择的对应系统的 ID

            # 根据付款条件的 ID 获取对应的 PaymentTerm 对象
            payment_terms = PaymentTerm.objects.get(pk=payment_terms_id)

            doc = Document.objects.create(
                document_type=document.content_type,
                document_name=document_name,
                uploader=uploader,
                document_file=document,
                contract_category=contract_category,
                contract_signature_date=contract_signature_date,
                contract_expiry_date=contract_expiry_date,
                contract_amount_with_tax=contract_amount_with_tax,
                contract_amount_without_tax=contract_amount_without_tax,
                payment_terms=payment_terms  # 保存付款条件对象
            )
            return redirect('upload_document')

    return render(request, 'doc_management/upload_document.html', {'existing_payment_terms': existing_payment_terms})


def batch_upload_document(request):
    if request.method == 'POST':
        documents = request.FILES.getlist('document')

        uploaded_count = 0
        for document in documents:
            try:
                document_name = document.name
                uploader = request.user

                if Document.objects.filter(document_name=document_name).exists():
                    message = f"已上传过相同名称的文件: {document_name}"
                    return render(request, 'doc_management/batch_upload_document.html', {'message': message})

                # 获取用户输入的新字段值
                contract_category = request.POST.get('contract_category')

                Document.objects.create(
                    document_type=document.content_type,
                    document_name=document_name,
                    uploader=uploader,
                    document_file=document,
                    contract_category=contract_category
                )
                uploaded_count += 1
            except Exception as e:
                print(f"上传文件 {document_name} 时出现异常: {str(e)}")

        message = f"成功上传了 {uploaded_count} 个文件。"
        return redirect('home')

    return render(request, 'doc_management/batch_upload_document.html')


def delete_document(request, document_id):
    document = get_object_or_404(Document, id=document_id)
    document_path = document.document_file.path

    try:
        if os.path.exists(document_path):
            os.remove(document_path)
    except:
        pass

    document.delete()

    return redirect('home')


@login_required
def preview_document(request, document_id):
    document = get_object_or_404(Document, id=document_id)
    file_path = document.document_file.path
    extension = os.path.splitext(file_path)[1].lower()

    if extension == ".pdf":
        try:
            with open(file_path, 'rb') as file:
                content = file.read()
                response = HttpResponse(content, content_type='application/pdf')
                response['Content-Disposition'] = f'inline; filename="{document.document_name}"'
                return response
        except FileNotFoundError:
            return HttpResponse("找不到文件。")
    elif extension in [".docx", ".doc", ".xlsx", ".xls", ".pptx", ".ppt"]:
        try:
            # Convert the document to PDF using docx2pdf
            pdf_content = convert_to_pdf(file_path)
            response = HttpResponse(pdf_content, content_type='application/pdf')
            response['Content-Disposition'] = f'inline; filename="{document.document_name}.pdf"'
            return response
        except Exception as e:
            return HttpResponse(f"预览失败：{str(e)}")
    else:
        return HttpResponse("不支持的文件类型。")


def convert_to_pdf(input_file_path):
    with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as temp_pdf_file:
        temp_pdf_path = temp_pdf_file.name
    convert(input_file_path, temp_pdf_path)  # Use docx2pdf to convert
    with open(temp_pdf_path, 'rb') as pdf_file:
        pdf_content = pdf_file.read()
    os.remove(temp_pdf_path)
    return pdf_content


def request_preview(request, document_id):
    document = get_object_or_404(Document, id=document_id)

    if request.user != document.uploader and not PreviewRequest.objects.filter(requester=request.user,
                                                                               document=document).exists():
        preview_request = PreviewRequest.objects.create(
            requester=request.user,
            document=document,
            approved_by=None,
            is_approved=False,
            created_at=timezone.now(),
        )

        document.requested_for_preview = True
        document.save()

    return redirect('home')


def edit_document(request, document_id):
    document = get_object_or_404(Document, id=document_id)
    existing_payment_terms = PaymentTerm.objects.all()

    if request.method == 'POST':
        contract_category = request.POST.get('contract_category')
        contract_signature_date = request.POST.get('contract_signature_date')
        contract_expiry_date = request.POST.get('contract_expiry_date')
        contract_amount_with_tax = request.POST.get('contract_amount_with_tax')
        contract_amount_without_tax = request.POST.get('contract_amount_without_tax')
        payment_terms_id = request.POST.get('payment_terms')

        payment_terms = PaymentTerm.objects.get(pk=payment_terms_id)

        document.contract_category = contract_category
        document.contract_signature_date = contract_signature_date
        document.contract_expiry_date = contract_expiry_date
        document.contract_amount_with_tax = contract_amount_with_tax
        document.contract_amount_without_tax = contract_amount_without_tax
        document.payment_terms = payment_terms
        document.save()

        return redirect('home')
    else:
        # 如果日期字段为None，则设置一个适当的默认值
        if document.contract_signature_date is None:
            document.contract_signature_date = datetime.date.today()

        if document.contract_expiry_date is None:
            document.contract_expiry_date = datetime.date.today()

        return render(request, 'doc_management/edit_document.html', {
            'document': document,
            'existing_payment_terms': existing_payment_terms
        })


def payment_terms_list(request):
    payment_terms = PaymentTerm.objects.all()
    return render(request, 'doc_management/payment_terms_list.html', {'payment_terms': payment_terms})


def add_payment_term(request):
    if request.method == 'POST':
        abbreviation = request.POST.get('abbreviation')
        description = request.POST.get('description')
        PaymentTerm.objects.create(abbreviation=abbreviation, description=description)
        return redirect('payment_terms_list')
    return render(request, 'doc_management/add_payment_term.html')


def edit_payment_term(request, payment_term_id):
    payment_term = get_object_or_404(PaymentTerm, id=payment_term_id)
    if request.method == 'POST':

document_management/templates/doc_management/add_payment_term.html
<!DOCTYPE html>
<html>
<head>
    <title>添加新对应系统</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f2f2f2;
        }
        h1 {
            text-align: center;
            margin: 20px 0;
            color: #333;
        }
        form {
            max-width: 400px;
            margin: 0 auto;
            background-color: #ffffff;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        label {
            display: block;
            font-weight: bold;
            margin-bottom: 10px;
            color: #333;
        }
        input[type="text"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ccc;
            border-radius: 3px;
        }
        .button-container {
            display: flex;
            justify-content: center; /* 按钮右对齐 */
            margin-top: 20px;
        }
        button[type="submit"],
        a.button {
            background-color: #007BFF;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 3px;
            cursor: pointer;
            text-decoration: none;
            font-size: 16px;
            margin-left: 10px; /* 按钮之间的间距 */
            transition: background-color 0.3s;
        }
        button[type="submit"]:hover,
        a.button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <h1>添加新对应系统</h1>
    <form method="post">
        {% csrf_token %}
        <label for="abbreviation">简称：</label>
        <input type="text" id="abbreviation" name="abbreviation" required>
        <label for="description">详细描述：</label>
        <input type="text" id="description" name="description" required>
        <div class="button-container">
            <button type="submit">添加</button>
            <a href="{% url 'payment_terms_list' %}" class="button">返回</a>
        </div>
    </form>
</body>
</html>

document_management/templates/doc_management/batch_upload_document.html
<!DOCTYPE html>
<html>
<head>
    <title>批量上传文档</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }
        header {
            background-color: #333;
            color: #fff;
            padding: 10px;
            text-align: center;
        }
        main {
            padding: 20px;
        }
        main h1 {
            margin-bottom: 20px;
        }
        main form {
            max-width: 400px;
            margin: 0 auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }
        main form label {
            display: block;
            margin-bottom: 10px;
            font-weight: bold;
        }
        main form input[type="text"],
        main form input[type="file"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 20px;
            border: 1px solid #ccc;
            border-radius: 3px;
        }
        main form input[type="submit"],
        main form a.button {
            background-color: #007BFF;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 3px;
            cursor: pointer;
            text-decoration: none;
            font-size: 16px; /* 设置按钮字体大小 */
        }
        main form input[type="submit"]:hover,
        main form a.button:hover {
            background-color: #0056b3;
        }
        main .message {
            color: green;
            margin-top: 10px;
            font-weight: bold;
        }
        .button + .button {
            margin-left: 10px; /* 设置按钮之间的左边距 */
        }

    </style>
</head>
<body>
    <header>
        <h1>批量上传文档</h1>
    </header>
    <main>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <label for="document">选择多个文档:</label>
            <input type="file" name="document" id="document" multiple>
            <br>

   <label for="contract_category" style="display: flex; align-items: center;">文档分类:
    <select name="contract_category" id="contract_category" style="margin-left: 10px;">
        <option value="paper">纸质文档</option>
        <option value="electronic">电子文档</option>
    </select>
        </label>
         <br>
            <!-- 使用 flex 布局来对齐按钮 -->
            <div style="display: flex; align-items: center;">
                <input type="submit" value="批量上传" class="button">
                <!-- 返回按钮 -->
                <a href="{% url 'home' %}" class="button">返回</a>
            </div>
        </form>
        {% if message %}
            <div class="message">{{ message }}</div>
        {% endif %}
    </main>
</body>
</html>

document_management/templates/doc_management/delete_payment_term.html
<!DOCTYPE html>
<html>
<head>
    <title>确认删除对应系统</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f2f2f2;
        }
        h1 {
            text-align: center;
            margin: 20px 0;
            color: #333;
        }
        p {
            text-align: center;
            margin-bottom: 20px;
            color: #555;
        }
        form {
            max-width: 400px;
            margin: 0 auto;
            background-color: #ffffff;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            text-align: center;
        }
        button[type="submit"],
        a.button {
            background-color: #007BFF;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 3px;
            cursor: pointer;
            text-decoration: none;
            font-size: 16px;
            margin-right: 10px;
            transition: background-color 0.3s;
        }
        button[type="submit"]:hover,
        a.button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <h1>确认删除对应系统</h1>
    <p>确定要删除对应系统 {{ payment_term.abbreviation }} - {{ payment_term.description }} 吗？</p>
    <form method="post">
        {% csrf_token %}
        <div class="button-container">
            <button type="submit">确认删除</button>
            <a href="{% url 'payment_terms_list' %}" class="button">取消</a>
        </div>
    </form>
</body>
</html>

document_management/templates/doc_management/edit_payment_term.html
<!DOCTYPE html>
<html>
<head>
    <title>编辑对应系统</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f2f2f2;
        }
        h1 {
            text-align: center;
            margin: 20px 0;
            color: #333;
        }
        form {
            max-width: 400px;
            margin: 0 auto;
            background-color: #ffffff;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        label {
            display: block;
            font-weight: bold;
            margin-bottom: 10px;
            color: #333;
        }
        input[type="text"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ccc;
            border-radius: 3px;
        }
        button[type="submit"],
        a.button {
            background-color: #007BFF;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 3px;
            cursor: pointer;
            text-decoration: none;
            font-size: 16px;
            margin-left: 10px; /* 按钮之间的间距 */
            transition: background-color 0.3s;
        }
        button[type="submit"]:hover,
        a.button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <h1>编辑对应系统</h1>
    <form method="post">
        {% csrf_token %}
        <label for="abbreviation">简称：</label>
        <input type="text" id="abbreviation" name="abbreviation" value="{{ payment_term.abbreviation }}" required>
        <label for="description">详细描述：</label>
        <input type="text" id="description" name="description" value="{{ payment_term.description }}" required>
        <div class="button-container">
            <button type="submit">保存</button>
            <a href="{% url 'payment_terms_list' %}" class="button">返回</a>
        </div>
    </form>
</body>
</html>

document_management/templates/doc_management/home.html
<!DOCTYPE html>
<html>
<head>
    <title>欢迎使用资源文档管理平台</title>
    <style>
        /* 设置页面的基本样式 */
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }
        /* 设置页眉样式 */
        header {
            background-color: #333;
            color: #fff;
            padding: 10px;
            text-align: center;
        }
        /* 设置导航栏样式 */
        nav {
            float: left;
            width: 200px;
            background-color: #f1f1f1;
            height: 84vh;
            padding: 20px;
        }
        nav ul {
            list-style: none;
            padding: 0;
        }
        nav ul li {
            margin-bottom: 10px;
        }
        nav ul li a {
            color: #333;
            text-decoration: none;
            display: block;
            padding: 5px;
        }
        nav ul li a:hover {
            background-color: #ddd;
        }
        /* 设置子菜单样式 */
        .submenu {
            padding-left: 20px;
            display: none;
        }
        .active .submenu {
            display: block;
        }
        /* 设置主内容区样式 */
        main {
            margin-left: 220px;
            padding: 20px;
        }
        main h1 {
            margin-bottom: 20px;
        }
        main ul {
            list-style: none;
            padding: 0;
        }
        main ul li {
            margin-bottom: 10px;
        }
        main a {
            color: #007BFF;
            text-decoration: none;
        }
        /* 设置表格样式 */
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: center;
        }
        th {
            background-color: #f2f2f2;
        }
        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
        /* 设置用户信息和退出按钮样式 */
        .user-info {
            position: absolute;
            top: 10px;
            right: 20px;
            display: flex;
            align-items: center;
            color: #fff;
        }
        .user-info a {
            color: #fff;
            text-decoration: none;
            margin-left: 10px;
        }
        .qq-group {
            float: left;
            margin-right: 10px;
            padding: 20px 0;
        }
    </style>
    <script>
        function toggleSubMenu(event) {
            const parentItem = event.target.parentElement;
            parentItem.classList.toggle('active');
        }

        function confirmLogout() {
            var confirmResult = confirm("确认退出系统吗？");
            if (confirmResult) {
                window.location.href = "{% url 'login' %}";
            }
        }

        // 添加搜索功能
        function searchDocuments() {
            const searchTerm = document.getElementById('document-search').value.toLowerCase();
            const documentRows = document.querySelectorAll('tr:not(:first-child)');

            documentRows.forEach(row => {
                const documentName = row.querySelector('td:first-child').textContent.toLowerCase();

                if (documentName.includes(searchTerm)) {
                    row.style.display = 'table-row';
                } else {
                    row.style.display = 'none';
                }
            });
        }

        // 添加文档类型筛选功能
        function filterByContractType() {
            const selectedType = document.getElementById('contract-type-filter').value;
            const documentRows = document.querySelectorAll('tr:not(:first-child)');

            documentRows.forEach(row => {
                const contractType = row.querySelector('td:nth-child(2)').textContent;

                if (selectedType === '' || contractType === selectedType) {
                    row.style.display = 'table-row';
                } else {
                    row.style.display = 'none';
                }
            });
        }
    </script>
</head>
<body>
    <header>
        <h1>欢迎使用资源文档管理平台</h1>
        <div class="user-info">
            <p>欢迎您登陆：{{ user.full_name }}</p>
            <a href="{% url 'admin:index' %}" style="margin-left: 10px;">进入管理台</a>
            <a href="#" onclick="confirmLogout()">退出</a>
        </div>
    </header>
    <nav>
        <ul>
            <li><a href="#" onclick="toggleSubMenu(event)">文档管理</a>
                <ul class="submenu">
                    <li><a href="{% url 'home' %}">文档列表</a></li>
                    <li><a href="{% url 'upload_document' %}">上传文档</a></li>
                    <li><a href="{% url 'batch_upload_document' %}">批量上传</a></li>
                    <li><a href="{% url 'payment_terms_list' %}">对应系统</a></li>
                </ul>
            </li>
            {% if request.user.is_superuser %}
            <li><a href="#" onclick="toggleSubMenu(event)">用户管理</a>
                <ul class="submenu">
                    <li><a href="{% url 'user_list' %}">用户列表</a></li>
                    <li><a href="{% url 'add_user' %}">新增用户</a></li>
                    <li><a href="{% url 'department_settings' %}">新增部门</a></li>
                    <li><a href="{% url 'department_list' %}">部门列表</a></li>
                </ul>
            </li>
            {% endif %}
            <li><a href="#" onclick="toggleSubMenu(event)">系统配置</a>
                <ul class="submenu">
                    <li><a href="{% url 'user_info' %}">用户信息</a></li>
                    <li><a href="{% url 'change_password' %}">修改密码</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <h1 style="margin: 8px 0;">文档列表</h1>
    <input type="text" id="document-search" placeholder="搜索文件" oninput="searchDocuments()" style="height: 30px; width: 200px; padding: 5px; border: 1px solid #D3D3D3; border-radius: 7px;">
    <label for="contract-type-filter" style="margin-left: 20px;">文档类型：</label>
    <select id="contract-type-filter" onchange="filterByContractType()">
        <option value="">全部</option>
        <option value="纸质文档">纸质文档</option>
        <option value="电子文档">电子文档</option>
    </select>
    <main style="margin-top: -40px;">
        <table>
            <tr>
                <th>文件名称</th>
                <th>文档类型</th>
                <th>上传人</th>
                <th>上传时间</th>
                <th>文档签订日期</th>
                <th>文档失效日期</th>
                <th>文档备注</th>
                <th>文档备注</th>
                <th>对应系统</th>
                <th>操作</th>
            </tr>
            {% for document in page_documents %}
            <tr>
                <td>{{ document.document_name }}</td>
                <td>{{ document.get_contract_category_display }}</td>
                <td>{{ document.uploader }}</td>
                <td>{{ document.uploaded_at|date:"Y-m-d H:i:s" }}</td>
                <td>{{ document.contract_signature_date|date:"Y-m-d" }}</td>
                <td>{{ document.contract_expiry_date|date:"Y-m-d" }}</td>
                <td>{{ document.contract_amount_with_tax }}</td>
                <td>{{ document.contract_amount_without_tax }}</td>
                <td>{{ document.payment_terms }}</td>
                <td>
                    {% if request.user.is_superuser or document.uploader == request.user %}
                    <a href="{% url 'preview_document' document.id %}" target="_blank">预览</a>
                    <a href="{% url 'edit_document' document.id %}" class="edit-btn">编辑</a>
                    <a href="{% url 'delete_document' document.id %}" onclick="return confirm('确认要删除该文档吗？')">删除</a>
                    {% endif %}
                    {% if not request.user.is_superuser %}
                    {% if document.uploader != request.user %}
                    {% if document.is_approved_for_preview %}
                    <a href="{% url 'preview_document' document.id %}" target="_blank">预览</a>
                    {% elif document.is_waiting_approval %}
                    <a href="#" style="color: gray;">等待审批</a>
                    {% else %}
                    <a href="{% url 'request_preview' document.id %}" style="color: red;">预览申请</a>
                    {% endif %}
                    {% endif %}
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>
        <div class="pagination">
            {% if page_documents.has_previous %}
            <a href="?page=1">&laquo; 第一页</a>
            <a href="?page={{ page_documents.previous_page_number }}">上一页</a>
            {% endif %}
            <span class="current-page">{{ page_documents.number }} / {{ page_documents.paginator.num_pages }} 页</span>
            {% if page_documents.has_next %}
            <a href="?page={{ page_documents.next_page_number }}">下一页</a>
            <a href="?page={{ page_documents.paginator.num_pages }}">最后一页 &raquo;</a>
            {% endif %}
        </div>
    </main>
</body>
</html>